version: "3"

services:
  mongodb:
    hostname: localhost
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - 27017:27017
  api-simulator-loan:
    image: api-simulator-loan:1.0
    container_name: api-simulator-loan
    ports:
      - 9191:8080
    links:
      - mongodb
    depends_on:
      - vault